export const UNITS = [
  {
    name: "Mournfang x 4",
    uuid: "ufOcC0V64r051Y_Z93IiM",
    numModels: 1,
    numLeaders: 1,
    weaponProfiles: [
      // {
      //   active: true,
      //   num_models: 1,
      //   attacks: 1,
      //   to_hit: 4,
      //   to_wound: "3",
      //   rend: "1",
      //   damage: 1,
      //   modifiers: [],
      //   uuid: "0FrkWuDFxLcEyEgtC7q72",
      //   name: "Pistol",
      // },
      {
        // active: true,
        // num_models: 4,
        attacks: 4,
        to_hit: 3,
        to_wound: 3,
        rend: 1,
        damage: 2,
        // modifiers: [
        //   {
        //     id: "LEADER_BONUS",
        //     options: { characteristic: "attacks", bonus: 1, numLeaders: 1 },
        //     uuid: "U7a080c94-PGSI9JEOOht",
        //     active: true,
        //   },
        // ],
        uuid: "7bU9x7nj9adtITim1Tdy6",
        name: "clubs",
      },
      {
        // active: true,
        // num_models: 4,
        attacks: 4,
        to_hit: 4,
        to_wound: 3,
        rend: 1,
        damage: 2,
        modifiers: [],
        uuid: "fb9sEWK1SPEFId1JzfodN",
        name: "Tusks",
      },
    ],
  },
  {
    name: "Mournfang x 2",
    uuid: "ufOcC0V64r05qweq1Y_Z93IiM",
    numModels: 1,
    numLeaders: 1,
    weaponProfiles: [
      // {
      //   active: true,
      //   num_models: 1,
      //   attacks: 1,
      //   to_hit: 4,
      //   to_wound: "3",
      //   rend: "1",
      //   damage: 1,
      //   modifiers: [],
      //   uuid: "0FrkWuDFxLcEyEgtC7q72",
      //   name: "Pistol",
      // },
      {
        // active: true,
        // num_models: 4,
        attacks: 4,
        to_hit: 3,
        to_wound: 3,
        rend: 1,
        damage: 2,
        // modifiers: [
        //   {
        //     id: "LEADER_BONUS",
        //     options: { characteristic: "attacks", bonus: 1, numLeaders: 1 },
        //     uuid: "U7a080c94-PGSI9JEOOht",
        //     active: true,
        //   },
        // ],
        uuid: "7bU9x7nj9adtITim1Tdy6",
        name: "clubs",
      },
      {
        // active: true,
        // num_models: 4,
        attacks: 4,
        to_hit: 4,
        to_wound: 3,
        rend: 1,
        damage: 2,
        modifiers: [],
        uuid: "fb9sEWK1SPEFId1JzfodN",
        name: "Tusks",
      },
    ],
  },
  {
    name: "Mournfang x 2",
    uuid: "ufOcC0V64r051Y_Zeq93IiM",
    numModels: 1,
    numLeaders: 1,
    weaponProfiles: [
      // {
      //   active: true,
      //   num_models: 1,
      //   attacks: 1,
      //   to_hit: 4,
      //   to_wound: "3",
      //   rend: "1",
      //   damage: 1,
      //   modifiers: [],
      //   uuid: "0FrkWuDFxLcEyEgtC7q72",
      //   name: "Pistol",
      // },
      {
        // active: true,
        // num_models: 4,
        attacks: 4,
        to_hit: 3,
        to_wound: 3,
        rend: 1,
        damage: 2,
        // modifiers: [
        //   {
        //     id: "LEADER_BONUS",
        //     options: { characteristic: "attacks", bonus: 1, numLeaders: 1 },
        //     uuid: "U7a080c94-PGSI9JEOOht",
        //     active: true,
        //   },
        // ],
        uuid: "7bU9x7nj9adtITim1Tdy6",
        name: "clubs",
      },
      {
        // active: true,
        // num_models: 4,
        attacks: 4,
        to_hit: 4,
        to_wound: 3,
        rend: 1,
        damage: 2,
        modifiers: [],
        uuid: "fb9sEWK1SPEFId1JzfodN",
        name: "Tusks",
      },
    ],
  },
];
